Develop
sbisaria/Tavisca.MentorAssignments pull request #1
Opened 2017-08-04 14:30 UTC by sbisaria

@tavisca-prathod

2017-08-06 05:24 UTC, tavisca-prathod commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/BatteryCharacterstics.cs
> +        public double IdleHours { get; set; }
missing model?

2017-08-06 05:26 UTC, tavisca-prathod commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/MobileDisplayCharacterstic.cs
> +    public class MobileDisplayCharacterstic
Class name can be MobileDisplay

2017-08-06 05:34 UTC, tavisca-prathod commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/MobileDisplayCharacterstic.cs
> +            colour = Colours;
string colour is assigned to List<string>colours.

2017-08-06 05:36 UTC, tavisca-prathod commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/Gsm.cs
> +        public Battery Battery;
any reason why getter and setter are not there here ?

2017-08-06 06:03 UTC, sbisaria commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/MobileDisplayCharacterstic.cs
> +            colour = Colours;
should i do this:

public double Size { get; set; }
        public List<string> Colours { get; set; }

        public MobileDisplay(double size,List<string> colour)
        {
            size = Size;
            colour = Colours;
        }

2017-08-06 06:04 UTC, sbisaria commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/MobileDisplayCharacterstic.cs
> +            colour = Colours;
public double Size { get; set; }
        public List<string> Colours { get; set; }

        public MobileDisplayCharacterstic(double size, List<string> colour)
        {
            size = Size;
            colour = Colours;
        }

2017-08-06 06:08 UTC, sbisaria commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/MobileDisplayCharacterstic.cs
> +            colour = Colours;
Is this correct

2017-08-06 06:35 UTC, tavisca-prathod commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/MobileDisplayCharacterstic.cs
> +            colour = Colours;
yes

2017-08-07 04:34 UTC, tavisca-prathod requested changes

2017-08-07 04:34 UTC, tavisca-prathod commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/BatteryCharacterstics.cs
> +        public double IdleHours { get; set; }
You are missing Model property.

2017-08-07 06:25 UTC, tavisca-prathod requested changes

2017-08-07 06:25 UTC, tavisca-prathod commented on Tavisca.MobileInfoManager/MobileInfoManager.Entity/BatteryCharacterstics.cs
> +        public MobileDevice Model { get; set; }
Why Model is of type MobileDevice ?

2017-08-14 04:40 UTC, closed without merging